const int lowestPin = PIN_PD1;
const int highestPin = PIN_PD3;

void setup() {
  // Re-route the signal generated by TCA0 to PORTD (which includes PD1, PD2, PD3)
  PORTMUX.TCAROUTEA = PORTMUX_TCA0_PORTD_gc;
}

void loop() {
// Iterate over the pins (Red -> Green -> Blue):
  for (int thisPin = lowestPin; thisPin <= highestPin; thisPin++) {
    // Fade the LED on thisPin (Red, Green, or Blue) from off to brightest:
    for (int brightness = 0; brightness < 255; brightness++) {
      analogWrite(thisPin, brightness); // Adjust brightness for this pin
      delay(2); // Delay to control the fade speed
    }
    // Fade the LED on thisPin (Red, Green, or Blue) from brightest to off:
    for (int brightness = 255; brightness >= 0; brightness--) {
      analogWrite(thisPin, brightness); // Adjust brightness for this pin
      delay(2); // Delay to control the fade speed
    }
    // Pause between color changes:
    delay(100); // Delay before fading the next color
  }
}